# Generated by Django 5.1.7 on 2025-04-03 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mentorados", "0003_disponibilidade"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Disponibilidade",
            new_name="DisponibilidadeHorarios",
        ),
    ]
